name: plfp
description: Functional programming and some other utils
version: 1.0.0
repository: https://github.com/Parkour-Labs/plfp.git

environment:
  sdk: '>=2.13.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
